note
	description: "Test cases for simple_diff"
	author: "Generated by simple_codegen"
	date: "$Date$"
	revision: "$Revision$"

class
	LIB_TESTS

inherit
	TEST_SET_BASE

feature -- Basic Tests

	test_creation
			-- Test that main class can be created.
		local
			l_diff: SIMPLE_DIFF
		do
			create l_diff.make
			assert ("created", l_diff /= Void)
			assert ("default_context", l_diff.context_lines = 3)
			assert ("no_whitespace_ignore", not l_diff.ignore_whitespace)
			assert ("no_case_ignore", not l_diff.ignore_case)
		end

	test_diff_line_context
			-- Test context line creation.
		local
			l_line: DIFF_LINE
		do
			create l_line.make_context ("hello world", 5, 5)
			assert ("is_context", l_line.is_context)
			assert ("not_added", not l_line.is_added)
			assert ("not_removed", not l_line.is_removed)
			assert ("prefix_space", l_line.prefix_char = ' ')
			assert ("source_line", l_line.source_line_number = 5)
			assert ("target_line", l_line.target_line_number = 5)
		end

	test_diff_line_added
			-- Test added line creation.
		local
			l_line: DIFF_LINE
		do
			create l_line.make_added ("new line", 10)
			assert ("is_added", l_line.is_added)
			assert ("not_context", not l_line.is_context)
			assert ("not_removed", not l_line.is_removed)
			assert ("prefix_plus", l_line.prefix_char = '+')
			assert ("source_zero", l_line.source_line_number = 0)
			assert ("target_line", l_line.target_line_number = 10)
		end

	test_diff_line_removed
			-- Test removed line creation.
		local
			l_line: DIFF_LINE
		do
			create l_line.make_removed ("old line", 7)
			assert ("is_removed", l_line.is_removed)
			assert ("not_context", not l_line.is_context)
			assert ("not_added", not l_line.is_added)
			assert ("prefix_minus", l_line.prefix_char = '-')
			assert ("source_line", l_line.source_line_number = 7)
			assert ("target_zero", l_line.target_line_number = 0)
		end

feature -- Hunk Tests

	test_diff_hunk_creation
			-- Test hunk creation.
		local
			l_hunk: DIFF_HUNK
		do
			create l_hunk.make (1, 1)
			assert ("source_start", l_hunk.source_start = 1)
			assert ("target_start", l_hunk.target_start = 1)
			assert ("empty_lines", l_hunk.lines.is_empty)
			assert ("zero_additions", l_hunk.additions_count = 0)
			assert ("zero_deletions", l_hunk.deletions_count = 0)
		end

	test_diff_hunk_add_lines
			-- Test adding lines to hunk.
		local
			l_hunk: DIFF_HUNK
		do
			create l_hunk.make (1, 1)
			l_hunk.add_context_line ("line 1", 1, 1)
			l_hunk.add_removed_line ("old line", 2)
			l_hunk.add_added_line ("new line", 2)
			l_hunk.add_context_line ("line 3", 3, 3)

			assert ("four_lines", l_hunk.lines.count = 4)
			assert ("one_addition", l_hunk.additions_count = 1)
			assert ("one_deletion", l_hunk.deletions_count = 1)
			assert ("two_context", l_hunk.context_count = 2)
		end

	test_diff_hunk_header
			-- Test hunk header generation.
		local
			l_hunk: DIFF_HUNK
		do
			create l_hunk.make (5, 7)
			l_hunk.add_context_line ("ctx", 5, 7)
			l_hunk.add_removed_line ("old", 6)
			l_hunk.add_added_line ("new", 8)

			assert ("header_format", l_hunk.header.starts_with ("@@ -5,"))
			assert ("header_ends", l_hunk.header.ends_with (" @@"))
		end

feature -- Result Tests

	test_diff_result_empty
			-- Test empty diff result.
		local
			l_result: DIFF_RESULT
		do
			create l_result.make
			assert ("is_identical", l_result.is_identical)
			assert ("no_changes", not l_result.has_changes)
			assert ("zero_hunks", l_result.hunk_count = 0)
			assert ("zero_lines", l_result.line_count = 0)
		end

	test_diff_result_with_hunks
			-- Test diff result with hunks.
		local
			l_result: DIFF_RESULT
			l_hunk: DIFF_HUNK
		do
			create l_result.make_with_paths ("file1.txt", "file2.txt")
			create l_hunk.make (1, 1)
			l_hunk.add_removed_line ("old", 1)
			l_hunk.add_added_line ("new", 1)
			l_result.add_hunk (l_hunk)

			assert ("not_identical", not l_result.is_identical)
			assert ("has_changes", l_result.has_changes)
			assert ("one_hunk", l_result.hunk_count = 1)
			assert ("source_path", attached l_result.source_path as sp and then sp.same_string ("file1.txt"))
			assert ("target_path", attached l_result.target_path as tp and then tp.same_string ("file2.txt"))
		end

feature -- Engine Tests

	test_engine_identical_strings
			-- Test diffing identical strings.
		local
			l_engine: DIFF_ENGINE
			l_result: DIFF_RESULT
		do
			create l_engine.make
			l_engine.set_source_from_string ("line1%Nline2%Nline3")
			l_engine.set_target_from_string ("line1%Nline2%Nline3")
			l_result := l_engine.compute_diff
			assert ("identical", l_result.is_identical)
		end

	test_engine_simple_change
			-- Test diffing with one changed line.
		local
			l_engine: DIFF_ENGINE
			l_result: DIFF_RESULT
		do
			create l_engine.make
			l_engine.set_source_from_string ("line1%Nold%Nline3")
			l_engine.set_target_from_string ("line1%Nnew%Nline3")
			l_result := l_engine.compute_diff
			assert ("has_changes", l_result.has_changes)
			assert ("one_addition", l_result.additions_total >= 1)
			assert ("one_deletion", l_result.deletions_total >= 1)
		end

	test_engine_addition
			-- Test diffing with added lines.
		local
			l_engine: DIFF_ENGINE
			l_result: DIFF_RESULT
		do
			create l_engine.make
			l_engine.set_source_from_string ("line1%Nline2")
			l_engine.set_target_from_string ("line1%Nline2%Nline3")
			l_result := l_engine.compute_diff
			assert ("has_changes", l_result.has_changes)
			assert ("has_addition", l_result.additions_total >= 1)
		end

	test_engine_deletion
			-- Test diffing with removed lines.
		local
			l_engine: DIFF_ENGINE
			l_result: DIFF_RESULT
		do
			create l_engine.make
			l_engine.set_source_from_string ("line1%Nline2%Nline3")
			l_engine.set_target_from_string ("line1%Nline3")
			l_result := l_engine.compute_diff
			assert ("has_changes", l_result.has_changes)
			assert ("has_deletion", l_result.deletions_total >= 1)
		end

feature -- Facade Tests

	test_facade_diff_strings
			-- Test facade string diff.
		local
			l_diff: SIMPLE_DIFF
			l_result: DIFF_RESULT
		do
			create l_diff.make
			l_result := l_diff.diff_strings ("hello%Nworld", "hello%Nearth")
			assert ("has_changes", l_result.has_changes)
		end

	test_facade_identical_strings
			-- Test facade with identical strings.
		local
			l_diff: SIMPLE_DIFF
			l_result: DIFF_RESULT
		do
			create l_diff.make
			l_result := l_diff.diff_strings ("same%Ncontent", "same%Ncontent")
			assert ("identical", l_result.is_identical)
		end

	test_facade_builder_pattern
			-- Test builder pattern settings.
		local
			l_diff: SIMPLE_DIFF
			l_temp: SIMPLE_DIFF
		do
			create l_diff.make
			-- Builder pattern returns self, must capture result
			l_temp := l_diff.set_context_lines (5)
			l_temp := l_diff.set_ignore_whitespace (True)
			l_temp := l_diff.set_ignore_case (True)
			assert ("context_set", l_diff.context_lines = 5)
			assert ("whitespace_set", l_diff.ignore_whitespace)
			assert ("case_set", l_diff.ignore_case)
		end

feature -- Renderer Tests

	test_renderer_unified
			-- Test unified diff rendering.
		local
			l_result: DIFF_RESULT
			l_hunk: DIFF_HUNK
			l_renderer: DIFF_RENDERER
			l_output: STRING
		do
			create l_result.make_with_paths ("a.txt", "b.txt")
			create l_hunk.make (1, 1)
			l_hunk.add_removed_line ("old", 1)
			l_hunk.add_added_line ("new", 1)
			l_result.add_hunk (l_hunk)

			create l_renderer.make
			l_output := l_renderer.render_unified (l_result)
			assert ("has_minus_header", l_output.has_substring ("--- a.txt"))
			assert ("has_plus_header", l_output.has_substring ("+++ b.txt"))
			assert ("has_hunk_header", l_output.has_substring ("@@"))
		end

	test_renderer_html
			-- Test HTML rendering.
		local
			l_result: DIFF_RESULT
			l_renderer: DIFF_RENDERER
			l_output: STRING
		do
			create l_result.make
			create l_renderer.make
			l_output := l_renderer.render_html (l_result)
			assert ("is_html", l_output.has_substring ("<html>"))
			assert ("has_style", l_output.has_substring ("<style>"))
		end

feature -- JSON Output Test

	test_result_json
			-- Test JSON output.
		local
			l_result: DIFF_RESULT
			l_json: STRING
		do
			create l_result.make_with_paths ("src.txt", "dst.txt")
			l_json := l_result.to_json
			assert ("is_json", l_json.starts_with ("{"))
			assert ("has_identical", l_json.has_substring ("is_identical"))
		end

end
