note
	description: "Test runner application for simple_diff"
	author: "Generated by simple_codegen"
	date: "$Date$"
	revision: "$Revision$"

class
	TEST_APP

create
	make

feature {NONE} -- Initialization

	make
			-- Run the tests.
		do
			print ("Running SIMPLE_DIFF tests...%N%N")
			passed := 0
			failed := 0

			run_lib_tests

			print ("%N========================%N")
			print ("Results: " + passed.out + " passed, " + failed.out + " failed%N")

			if failed > 0 then
				print ("TESTS FAILED%N")
			else
				print ("ALL TESTS PASSED%N")
			end
		end

feature {NONE} -- Test Runners

	run_lib_tests
			-- Run LIB_TESTS test cases.
		do
			create lib_tests

			print ("=== Basic Tests ===%N")
			run_test (agent lib_tests.test_creation, "test_creation")
			run_test (agent lib_tests.test_diff_line_context, "test_diff_line_context")
			run_test (agent lib_tests.test_diff_line_added, "test_diff_line_added")
			run_test (agent lib_tests.test_diff_line_removed, "test_diff_line_removed")

			print ("%N=== Hunk Tests ===%N")
			run_test (agent lib_tests.test_diff_hunk_creation, "test_diff_hunk_creation")
			run_test (agent lib_tests.test_diff_hunk_add_lines, "test_diff_hunk_add_lines")
			run_test (agent lib_tests.test_diff_hunk_header, "test_diff_hunk_header")

			print ("%N=== Result Tests ===%N")
			run_test (agent lib_tests.test_diff_result_empty, "test_diff_result_empty")
			run_test (agent lib_tests.test_diff_result_with_hunks, "test_diff_result_with_hunks")

			print ("%N=== Engine Tests ===%N")
			run_test (agent lib_tests.test_engine_identical_strings, "test_engine_identical_strings")
			run_test (agent lib_tests.test_engine_simple_change, "test_engine_simple_change")
			run_test (agent lib_tests.test_engine_addition, "test_engine_addition")
			run_test (agent lib_tests.test_engine_deletion, "test_engine_deletion")

			print ("%N=== Facade Tests ===%N")
			run_test (agent lib_tests.test_facade_diff_strings, "test_facade_diff_strings")
			run_test (agent lib_tests.test_facade_identical_strings, "test_facade_identical_strings")
			run_test (agent lib_tests.test_facade_builder_pattern, "test_facade_builder_pattern")

			print ("%N=== Renderer Tests ===%N")
			run_test (agent lib_tests.test_renderer_unified, "test_renderer_unified")
			run_test (agent lib_tests.test_renderer_html, "test_renderer_html")

			print ("%N=== JSON Output Test ===%N")
			run_test (agent lib_tests.test_result_json, "test_result_json")
		end

feature {NONE} -- Implementation

	lib_tests: LIB_TESTS

	passed: INTEGER
	failed: INTEGER

	run_test (a_test: PROCEDURE; a_name: STRING)
			-- Run a single test and update counters.
		local
			l_retried: BOOLEAN
		do
			if not l_retried then
				a_test.call (Void)
				print ("  PASS: " + a_name + "%N")
				passed := passed + 1
			end
		rescue
			print ("  FAIL: " + a_name + "%N")
			failed := failed + 1
			l_retried := True
			retry
		end

end
