note
	description: "Test runner application for simple_diff"
	author: "Generated by simple_codegen"
	date: "$Date$"
	revision: "$Revision$"

class
	TEST_APP

create
	make

feature {NONE} -- Initialization

	make
			-- Run the tests.
		do
			print ("Running SIMPLE_DIFF tests...%N%N")
			passed := 0
			failed := 0

			run_lib_tests
			run_adversarial_tests
			run_stress_tests

			print ("%N========================%N")
			print ("Results: " + passed.out + " passed, " + failed.out + " failed%N")

			if failed > 0 then
				print ("TESTS FAILED%N")
			else
				print ("ALL TESTS PASSED%N")
			end
		end

feature {NONE} -- Test Runners

	run_lib_tests
			-- Run LIB_TESTS test cases.
		do
			create lib_tests

			print ("=== Basic Tests ===%N")
			run_test (agent lib_tests.test_creation, "test_creation")
			run_test (agent lib_tests.test_diff_line_context, "test_diff_line_context")
			run_test (agent lib_tests.test_diff_line_added, "test_diff_line_added")
			run_test (agent lib_tests.test_diff_line_removed, "test_diff_line_removed")

			print ("%N=== Hunk Tests ===%N")
			run_test (agent lib_tests.test_diff_hunk_creation, "test_diff_hunk_creation")
			run_test (agent lib_tests.test_diff_hunk_add_lines, "test_diff_hunk_add_lines")
			run_test (agent lib_tests.test_diff_hunk_header, "test_diff_hunk_header")

			print ("%N=== Result Tests ===%N")
			run_test (agent lib_tests.test_diff_result_empty, "test_diff_result_empty")
			run_test (agent lib_tests.test_diff_result_with_hunks, "test_diff_result_with_hunks")

			print ("%N=== Engine Tests ===%N")
			run_test (agent lib_tests.test_engine_identical_strings, "test_engine_identical_strings")
			run_test (agent lib_tests.test_engine_simple_change, "test_engine_simple_change")
			run_test (agent lib_tests.test_engine_addition, "test_engine_addition")
			run_test (agent lib_tests.test_engine_deletion, "test_engine_deletion")

			print ("%N=== Facade Tests ===%N")
			run_test (agent lib_tests.test_facade_diff_strings, "test_facade_diff_strings")
			run_test (agent lib_tests.test_facade_identical_strings, "test_facade_identical_strings")
			run_test (agent lib_tests.test_facade_builder_pattern, "test_facade_builder_pattern")

			print ("%N=== Renderer Tests ===%N")
			run_test (agent lib_tests.test_renderer_unified, "test_renderer_unified")
			run_test (agent lib_tests.test_renderer_html, "test_renderer_html")
			run_test (agent lib_tests.test_renderer_side_by_side, "test_renderer_side_by_side")
			run_test (agent lib_tests.test_renderer_colored, "test_renderer_colored")

			print ("%N=== JSON Output Test ===%N")
			run_test (agent lib_tests.test_result_json, "test_result_json")

			print ("%N=== Patch Applier Tests ===%N")
			run_test (agent lib_tests.test_patch_applier_creation, "test_patch_applier_creation")
			run_test (agent lib_tests.test_patch_apply_to_string, "test_patch_apply_to_string")
			run_test (agent lib_tests.test_patch_applier_dry_run, "test_patch_applier_dry_run")
			run_test (agent lib_tests.test_patch_applier_reverse, "test_patch_applier_reverse")

			print ("%N=== Edge Case Tests ===%N")
			run_test (agent lib_tests.test_empty_strings, "test_empty_strings")
			run_test (agent lib_tests.test_one_empty_string, "test_one_empty_string")
			run_test (agent lib_tests.test_single_line_change, "test_single_line_change")
			run_test (agent lib_tests.test_multiline_complex, "test_multiline_complex")

			print ("%N=== Object Comparison Tests (simple_reflection) ===%N")
			run_test (agent lib_tests.test_diff_objects_equal, "test_diff_objects_equal")
			run_test (agent lib_tests.test_diff_objects_different, "test_diff_objects_different")
			run_test (agent lib_tests.test_diff_objects_as_string, "test_diff_objects_as_string")
		end

	run_adversarial_tests
			-- Run ADVERSARIAL_TESTS test cases.
		do
			create adversarial_tests

			print ("%N=== Input Attack Tests ===%N")
			run_test (agent adversarial_tests.test_null_byte_in_content, "test_null_byte_in_content")
			run_test (agent adversarial_tests.test_control_characters, "test_control_characters")
			run_test (agent adversarial_tests.test_very_long_line, "test_very_long_line")
			run_test (agent adversarial_tests.test_many_lines, "test_many_lines")

			print ("%N=== Output Attack Tests ===%N")
			run_test (agent adversarial_tests.test_html_injection_content, "test_html_injection_content")
			run_test (agent adversarial_tests.test_json_special_chars, "test_json_special_chars")
			run_test (agent adversarial_tests.test_unicode_content, "test_unicode_content")

			print ("%N=== State Attack Tests ===%N")
			run_test (agent adversarial_tests.test_reuse_after_error, "test_reuse_after_error")
			run_test (agent adversarial_tests.test_multiple_diffs_same_instance, "test_multiple_diffs_same_instance")

			print ("%N=== Edge Case Tests ===%N")
			run_test (agent adversarial_tests.test_only_newlines, "test_only_newlines")
			run_test (agent adversarial_tests.test_trailing_newline_difference, "test_trailing_newline_difference")
			run_test (agent adversarial_tests.test_identical_large_files, "test_identical_large_files")

			print ("%N=== Patch Attack Tests ===%N")
			run_test (agent adversarial_tests.test_patch_context_mismatch, "test_patch_context_mismatch")
			run_test (agent adversarial_tests.test_reverse_patch, "test_reverse_patch")
		end

	run_stress_tests
			-- Run STRESS_TESTS test cases.
		do
			create stress_tests

			print ("%N=== Volume Tests ===%N")
			run_test (agent stress_tests.test_1000_lines, "test_1000_lines")
			run_test (agent stress_tests.test_2000_lines, "test_2000_lines")
			run_test (agent stress_tests.test_5000_lines, "test_5000_lines")

			print ("%N=== Worst Case Tests ===%N")
			run_test (agent stress_tests.test_completely_different_1000, "test_completely_different_1000")
		end

feature {NONE} -- Implementation

	lib_tests: LIB_TESTS
	adversarial_tests: ADVERSARIAL_TESTS
	stress_tests: STRESS_TESTS

	passed: INTEGER
	failed: INTEGER

	run_test (a_test: PROCEDURE; a_name: STRING)
			-- Run a single test and update counters.
		local
			l_retried: BOOLEAN
		do
			if not l_retried then
				a_test.call (Void)
				print ("  PASS: " + a_name + "%N")
				passed := passed + 1
			end
		rescue
			print ("  FAIL: " + a_name + "%N")
			failed := failed + 1
			l_retried := True
			retry
		end

end
